class StringConstants {
  static const googlePlayLink =
      'https://play.google.com/store/apps/details?id=com.adtip.app.adtip_app&hl=en-IN';

  static const List<String> profession = [
    'Human resources manager',
    'Interior designer',
    'Interpreter',
    'Journalist',
    'Judge',
    'Lawyer',
    'Librarian',
    'Management consultant',
    'Marketing manager',
    'Mathematician',
    'Mechanical engineer',
    'Musician',
    'Nurse',
    'Occupational therapist',
    'Optometrist',
    'Painter',
    'Pharmacist',
    'Photographer',
    'Physical therapist',
    'Physician assistant',
    'Pilot',
    'Plumber',
    'Police officer',
    'Politician',
    'Professor',
    'Psychologist',
    'Real estate agent',
    'Receptionist',
    'Sales representative',
    'Scientist',
    'Secretary',
    'Social media manager',
    'Software developer',
    'Surgeon',
    'Teacher',
    'Technical writer',
    'Travel agent',
    'Veterinarian',
    'Video editor',
    'Web developer',
    'Writer',
    'House-Wife',
    'Accountant',
    'Actor',
    'Architect',
    'Artist',
    'Athlete',
    'Author',
    'Baker',
    'Banker',
    'Barista',
    'Bartender',
    'Biologist',
    'Builder',
    'Business consultant',
    'Carpenter',
    'Chef',
    'Chemist',
    'Chiropractor',
    'Civil engineer',
    'Coach',
    'Computer programmer',
    'Construction worker',
    'Counselor',
    'Dentist',
    'Designer',
    'Detective',
    'Dietitian',
    'Doctor',
    'Economist',
    'Electrician',
    'Engineer',
    'Entrepreneur',
    'Farmer',
    'Fashion designer',
    'Film director',
    'Firefighter',
    'Fitness trainer',
    'Florist',
    'Geologist',
    'Graphic designer',
    'Hairdresser',
    'Historian',
    'Hotel manager',
  ];
}
